### ISSUE TITLE
add baseUrl or siteUrl to page configuration

### ISSUE THREAD

**Issue by johnpryan** [johnpryan/tavern-dart1#15]
In order to properly reference assets for any page, the tavern settings should be included in page metadata.  For example, instead of:

```
    <link rel="stylesheet" href="/style.css">
```

you could use a variable defined the page's metadata:

```
<link rel="stylesheet" href="{{site_url}}/style.css">
```

which would be configured in `pubspec.yaml`:

```
transformers:
- tavern:
    site_url: "http://localhost:8111/"
    sitemap_path: "/sitemap.xml"
    tag_page_index: "/tags/index.html"
```
